[package]
name = "babushka"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "^1.4"
bytes = "^1.3"
futures = "^0.3"
lifeguard = "^0.6"
num-derive = "^0.3"
num-traits = "^0.2"
redis = { path = "../submodules/redis-rs/redis", features = ["aio", "tokio-comp"] }
signal-hook = "^0.3"
signal-hook-tokio = {version = "^0.3", features = ["futures-v0_3"] }
tokio = { version = "1", features = ["macros"] }
logger_core = {path = "../logger_core"}


[dev-dependencies]
ntest = "0.9.0"
rand = "0.8.5"
rsevents = "0.3.1"
socket2 = "0.4.7"
tempfile = "3.3.0"
