name: Install Redis

inputs:
    redis-version:
        description: "redis version to install"
        required: true
        type: string

env:
    CARGO_TERM_COLOR: always

runs:
    using: "composite"

    steps:
        - run: mkdir -p ~/redis-binaries/${{ inputs.redis-version }}
          shell: bash

        - uses: actions/checkout@v4
          with:
              submodules: recursive

        - uses: actions/cache@v3
          id: cache-redis
          with:
              path: |
                  ~/redis-binaries/${{ inputs.redis-version }}/redis-cli
                  ~/redis-binaries/${{ inputs.redis-version }}/redis-server
              key: ${{ runner.os }}-${{ inputs.redis-version }}-install-redis

        - name: Install redis
          shell: bash
          if: steps.cache-redis.outputs.cache-hit != 'true'
          run: |
              sudo apt-get update
              wget https://github.com/redis/redis/archive/${{ inputs.redis-version }}.tar.gz;
              tar -xzvf ${{ inputs.redis-version }}.tar.gz;
              pushd redis-${{ inputs.redis-version }} && BUILD_TLS=yes make && sudo mv src/redis-server src/redis-cli ~/redis-binaries/${{ inputs.redis-version }} && popd;

        - name: Copy executable to place
          shell: bash
          run: sudo cp ~/redis-binaries/${{ inputs.redis-version }}/redis-server ~/redis-binaries/${{ inputs.redis-version }}/redis-cli /usr/bin/
