name: Start self hosted EC2 runner

inputs:
    aws-region:
        description: AWS Region, e.g. us-east-1
        required: true
    role-to-assume:
        description: AWS Role for which to fetch credentials.
        required: true
    ec2-instance-id:
        description: AWS EC2 instance ID for the self hosted runner
        required: true

runs:
    using: "composite"
    steps:
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
              role-to-assume: ${{ inputs.role-to-assume }}
              aws-region: ${{ inputs.aws-region }}

        - name: Start EC2 self hosted runner
          shell: bash
          run: |
              sudo snap refresh
              sudo snap install aws-cli --classic
              command_id=$(aws ssm send-command --instance-ids ${{ inputs.ec2-instance-id }} --document-name StartGithubSelfHostedRunner --query Command.CommandId --output text)

              while [[ "$invoke_status" != "Success" && "$invoke_status" != "Failed" ]]; do
                invoke_status=$(aws ssm list-command-invocations --command-id $command_id --query 'CommandInvocations[0].Status' --output text)
                echo "Current Status: $invoke_status"
                if [[ "$invoke_status" != "Success" && "$invoke_status" != "Failed" ]]; then
                    echo "Waiting for command to complete... Command ID: $command_id"
                    sleep 10
                    retry_counter=$((retry_counter+1))
                fi
                if (( retry_counter >= 100 )); then
                    echo "Reached maximum retries, status is: $invoke_status. Exiting..."
                    exit 1
                fi
                done

                echo "Final Command Status: $invoke_status"
