[package]
name = "logger_core"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]


[dependencies]
tracing = "0.1"
tracing-appender = "0.2.2"
once_cell = "1.16.0"
tracing-subscriber = "0.3.16"
