[build-system]
requires = ["setuptools>=61.0", "wheel", "cffi>=1.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "test-valkey-glide-sync"
version = "0.1.2"
description = "Valkey GLIDE Sync client (CFFI-based)"
requires-python = ">=3.9"
dependencies = [
    "cffi>=1.0.0",
    "protobuf>=6.20",
]

[tool.setuptools]
package-dir = {"" = "../../"}
include-package-data = true

[tool.setuptools.package-data]
"glide.sync" = ["*.so", "*.pyd", "*.dll", "*.pyi", "py.typed"]

[tool.setuptools.packages.find]
where = ["../../"]
exclude = ["glide", "glide/__init__.py", "glide/sync/build/**", "glide.shared.commands.aio*", "glide.aio*"]  # <â€“ exclude top-level glide, async, etc.
