site_name: GLIDE for Valkey - API Documentation
site_url: https://valkey.io/valkey-glide
repo_url: https://github.com/valkey-io/valkey-glide
repo_name: GitHub
docs_dir: markdown
nav:
  - Python:
      - Python async:
        - Client:
            - Standalone: python/async/glide_client.md
            - Cluster: python/async/glide_cluster_client.md
            - Base: python/async/base_client.md
        - Config: python/shared/config.md
        - Commands:
            - Core Commands: python/async/core.md
            - Cluster Commands: python/async/cluster_commands.md
            - Standalone Commands: python/async/standalone_commands.md
            - Base Batch: python/shared/base_batch.md
            - Standalone Batch: python/shared/standalone_batch.md
            - Cluster Batch: python/shared/cluster_batch.md
        - Lua Scripting: python/lua-scripts-guide.md
      - Python sync:
            - Client:
              - Standalone: python/sync/glide_client.md
              - Cluster: python/sync/glide_cluster_client.md
              - Base: python/sync/base_client.md
            - Config: python/sync/config.md
            - Commands:
                - Core Commands: python/sync/core.md
                - Cluster Commands: python/sync/cluster_commands.md
                - Standalone Commands: python/sync/standalone_commands.md
                - Base Batch: python/shared/base_batch.md
                - Standalone Batch: python/shared/standalone_batch.md
                - Cluster Batch: python/shared/cluster_batch.md
            - Lua Scripting: python/sync/lua-scripts-guide.md
      - Logger: python/shared/logger.md
      - Exceptions: python/shared/exceptions.md
  - TypeScript:
      - Client and Commands:
          - Standalone: node/GlideClient/classes/GlideClient.md
          - Cluster: node/GlideClusterClient/classes/GlideClusterClient.md
          - Base: node/BaseClient/classes/BaseClient.md
          - Base Batch: node/Batch/classes/BaseBatch.md
          - Standalone Batch: node/Batch/classes/Batch.md
          - Cluster Batch: node/Batch/classes/ClusterBatch.md
      - config: node/BaseClient/interfaces/BaseClientConfiguration.md
      - Modules:
          - JSON: node/server-modules/GlideJson/classes/GlideJson.md
          - Vector Search: node/server-modules/GlideFt/classes/GlideFt.md
      - Errors:
          - ClosingError: node/Errors/classes/ClosingError.md
          - ConfigurationError: node/Errors/classes/ConfigurationError.md
          - ConnectionError: node/Errors/classes/ConnectionError.md
          - ExecAbortError: node/Errors/classes/ExecAbortError.md
          - RequestError: node/Errors/classes/RequestError.md
          - TimeoutError: node/Errors/classes/TimeoutError.md
          - ValkeyError: node/Errors/classes/ValkeyError.md
      - Logger: node/Logger/classes/Logger.md
theme:
  name: material
  palette: 
    scheme: valkey-glide
  features:
    - navigation.sections
    - content.code.copy
    - navigation.path
    - navigation.footer
    - navigation.top
  highlightjs: true
  font:
    text: Roboto
    code: Roboto Mono
markdown_extensions:
  - pymdownx.keys
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_root_heading: true
  - search
  - mkdocs-breadcrumbs-plugin:
      delimiter: " / " # separator between sections
      log_level: "CRITICAL" # "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
      exclude_paths:
        - "docs/mkdocs/**"
        - "docs/mkdocs" # avoid generating index.md
      additional_index_folders:
        - temp_dir
      generate_home_index: false
  - redirects:
      redirect_maps:
        'index.md': 'https://glide.valkey.io/'
extra:
  generator: false
extra_css:
  - style.css
