name: Lint rust

inputs:
    cargo-toml-folder:
        description: "folder that contains the target Cargo.toml file"
        required: true
        type: string

runs:
    using: "composite"

    steps:
        - uses: actions/checkout@v4
          with:
              submodules: recursive

        - uses: dtolnay/rust-toolchain@stable
        - uses: Swatinem/rust-cache@v2

        - run: |
              sudo apt update
              sudo apt install protobuf-compiler
          shell: bash

        - run: cargo fmt --all -- --check
          working-directory: ${{ inputs.cargo-toml-folder }}
          shell: bash

        - run: cargo clippy --all-features --all-targets -- -D warnings
          working-directory: ${{ inputs.cargo-toml-folder }}
          shell: bash

        - run: |
              cargo update
              cargo install cargo-deny
              cargo deny check licenses --config ${GITHUB_WORKSPACE}/deny.toml
          working-directory: ${{ inputs.cargo-toml-folder }}
          shell: bash

        - name: doc
          shell: bash
          working-directory: ${{ inputs.cargo-toml-folder }}
          run: cargo doc --no-deps --document-private-items
          env:
              RUSTDOCFLAGS: -Dwarnings
