name: Lint rust

inputs:
    cargo-toml-folder:
        description: "folder that contains the target Cargo.toml file"
        required: true
        type: string

runs:
    using: "composite"

    steps:
        - uses: actions/checkout@v3

        - uses: actions-rs/toolchain@v1
          with:
              profile: minimal
              toolchain: stable
              override: true
              components: rustfmt, clippy

        - uses: Swatinem/rust-cache@v1

        - uses: actions-rs/cargo@v1
          with:
              command: fmt
              args: --manifest-path ${{ inputs.cargo-toml-folder }}/Cargo.toml --all -- --check

        - uses: actions-rs/cargo@v1
          with:
              command: clippy
              args: --manifest-path ${{ inputs.cargo-toml-folder }}/Cargo.toml --all-features --all-targets -- -D warnings
          
        - run: |
              cargo install cargo-deny
              cd ${{ inputs.cargo-toml-folder }}
              cargo deny check licenses
          env:
              RUSTFLAGS: --cfg tokio_unstable
          shell: bash

        - name: doc
          shell: bash
          working-directory: ${{ inputs.cargo-toml-folder }}
          run: cargo doc --no-deps --document-private-items
          env:
              RUSTDOCFLAGS: --Dwarnings
              RUSTFLAGS: --cfg tokio_unstable
